package Code;
public enum Sym {
	NOMBRE, AVANCER, TOURNER, ECRIRE, LIRE,
	LPAR, RPAR, PLUS, MOINS, SI, ALORS, FIN,
	TANTQUE, SUP, INF, EGALE, ET, Ou, ESSAYER,
	AVEC,PVIRG, EOF, RACC, LACC, FAIRE
}
